/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseInquiryResponse } from '../../models/page-response-inquiry-response';

export interface GetPagesOfInquiries$Params {
  type?: string;
  from_date?: string;
  page?: number;
  size?: number;
}

export function getPagesOfInquiries(http: HttpClient, rootUrl: string, params?: GetPagesOfInquiries$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseInquiryResponse>> {
  const rb = new RequestBuilder(rootUrl, getPagesOfInquiries.PATH, 'get');
  if (params) {
    rb.query('type', params.type, {});
    rb.query('from_date', params.from_date, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseInquiryResponse>;
    })
  );
}

getPagesOfInquiries.PATH = '/inquiries/pages';
