/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseUserResponse } from '../../models/page-response-user-response';

export interface FilterUsers$Params {
  branchId?: string;
  phone?: string;
  name?: string;
  page?: number;
  size?: number;
}

export function filterUsers(http: HttpClient, rootUrl: string, params?: FilterUsers$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseUserResponse>> {
  const rb = new RequestBuilder(rootUrl, filterUsers.PATH, 'get');
  if (params) {
    rb.query('branchId', params.branchId, {});
    rb.query('phone', params.phone, {});
    rb.query('name', params.name, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseUserResponse>;
    })
  );
}

filterUsers.PATH = '/identity/filter';
