/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseUserProfile } from '../../models/page-response-user-profile';

export interface GetPagesOfUser$Params {
  status?: 'OTP_SENT' | 'VERIFIED' | 'PROFILE_CREATED' | 'PENDING' | 'APPROVED' | 'ACTIVE' | 'DISABLED' | 'SUSPENDED' | 'REJECTED';
  email?: string;
  name?: string;
  page?: number;
  size?: number;
}

export function getPagesOfUser(http: HttpClient, rootUrl: string, params?: GetPagesOfUser$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseUserProfile>> {
  const rb = new RequestBuilder(rootUrl, getPagesOfUser.PATH, 'get');
  if (params) {
    rb.query('status', params.status, {});
    rb.query('email', params.email, {});
    rb.query('name', params.name, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseUserProfile>;
    })
  );
}

getPagesOfUser.PATH = '/identity/users';
