/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PreSignedUrlDto } from '../../models/pre-signed-url-dto';

export interface GetPresignedUrlToDelete$Params {
  file_name: string;
  folder: string;
}

export function getPresignedUrlToDelete(http: HttpClient, rootUrl: string, params: GetPresignedUrlToDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<PreSignedUrlDto>> {
  const rb = new RequestBuilder(rootUrl, getPresignedUrlToDelete.PATH, 'get');
  if (params) {
    rb.query('file_name', params.file_name, {});
    rb.query('folder', params.folder, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PreSignedUrlDto>;
    })
  );
}

getPresignedUrlToDelete.PATH = '/s3/presigned-delete-url';
