/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseStaffProfileResponse } from '../../models/page-response-staff-profile-response';

export interface GetPagesOfStaffProfile$Params {
  name?: string;
  position?: string;
  email?: string;
  phone?: string;
  department?: string;
  page?: number;
  size?: number;
}

export function getPagesOfStaffProfile(http: HttpClient, rootUrl: string, params?: GetPagesOfStaffProfile$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseStaffProfileResponse>> {
  const rb = new RequestBuilder(rootUrl, getPagesOfStaffProfile.PATH, 'get');
  if (params) {
    rb.query('name', params.name, {});
    rb.query('position', params.position, {});
    rb.query('email', params.email, {});
    rb.query('phone', params.phone, {});
    rb.query('department', params.department, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseStaffProfileResponse>;
    })
  );
}

getPagesOfStaffProfile.PATH = '/staff-profile/pages';
