/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateImpactStoryRequest } from '../../models/create-impact-story-request';

export interface UpdateImpactStory$Params {
  'public-id': string;
      body: CreateImpactStoryRequest
}

export function updateImpactStory(http: HttpClient, rootUrl: string, params: UpdateImpactStory$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
  const rb = new RequestBuilder(rootUrl, updateImpactStory.PATH, 'put');
  if (params) {
    rb.path('public-id', params['public-id'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      }>;
    })
  );
}

updateImpactStory.PATH = '/impact-story/update/{public-id}';
