/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseDocumentResponse } from '../../models/page-response-document-response';

export interface GetPagesOfDocuments$Params {
  title?: string;
  doc_type?: string;
  page?: number;
  size?: number;
}

export function getPagesOfDocuments(http: HttpClient, rootUrl: string, params?: GetPagesOfDocuments$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseDocumentResponse>> {
  const rb = new RequestBuilder(rootUrl, getPagesOfDocuments.PATH, 'get');
  if (params) {
    rb.query('title', params.title, {});
    rb.query('doc_type', params.doc_type, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseDocumentResponse>;
    })
  );
}

getPagesOfDocuments.PATH = '/documents/pages';
