/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuthTokens {
  accessToken?: string;
  isTempPassword?: boolean;
  refreshToken?: string;
  status?: 'OTP_SENT' | 'VERIFIED' | 'PROFILE_CREATED' | 'PENDING' | 'APPROVED' | 'ACTIVE' | 'DISABLED' | 'SUSPENDED' | 'REJECTED';
}
