/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreatStaffProfileRequest {
  bio?: string;
  department?: string;
  description?: string;
  displayOrder?: number;
  email?: string;
  firstName?: string;
  lastName?: string;
  linkedinUrl?: string;
  phone?: string;
  position?: string;
  profilePic?: string;
}
