/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateUserRequest {
  email: (string | null);
  firstName: string;
  lastName: string;
  remark?: string;
  role: 'SUPER_ADMIN' | 'ADMIN';
}
