/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateProgramRequest {
  description?: string;
  displayOrder?: number;
  logoUrl?: string;
  metricLabel?: string;
  metricNumber?: number;
  name?: string;
  status?: string;
}
