/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateDocumentRequest {
  description?: string;
  displayOrder?: number;
  documentType?: string;
  publishedDate?: string;
  thumbnailUrl?: string;
  title?: string;
  url?: string;
}
