/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StaffProfileResponse } from '../models/staff-profile-response';
export interface PageResponseStaffProfileResponse {
  content?: Array<StaffProfileResponse>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
