/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserProfile {
  createdAt?: string;
  email: string;
  firstName: string;
  isEmailVerified?: boolean;
  lastName: string;
  profilePic?: string;
  publicId: string;
  remark?: string;
  status: 'OTP_SENT' | 'VERIFIED' | 'PROFILE_CREATED' | 'PENDING' | 'APPROVED' | 'ACTIVE' | 'DISABLED' | 'SUSPENDED' | 'REJECTED';
  updatedAt?: string;
}
