/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserResponse {
  discipline?: string;
  name?: string;
  phone?: string;
  publicId?: string;
  role?: string;
}
