/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AuthenticationRequest } from './models/authentication-request';
export type { AuthTokens } from './models/auth-tokens';
export type { ChangePasswordRequest } from './models/change-password-request';
export type { CreateDocumentRequest } from './models/create-document-request';
export type { CreateImpactStoryRequest } from './models/create-impact-story-request';
export type { CreateInquiryRequest } from './models/create-inquiry-request';
export type { CreateProgramRequest } from './models/create-program-request';
export type { CreateUserRequest } from './models/create-user-request';
export type { CreatStaffProfileRequest } from './models/creat-staff-profile-request';
export type { DocumentResponse } from './models/document-response';
export type { EmailUpdateRequest } from './models/email-update-request';
export type { ForgetPasswordRequest } from './models/forget-password-request';
export type { GeneratePresignedUrlRequest } from './models/generate-presigned-url-request';
export type { ImpactStatisticsResponse } from './models/impact-statistics-response';
export type { ImpactStoryResponse } from './models/impact-story-response';
export type { InquiryResponse } from './models/inquiry-response';
export type { LogoutRequest } from './models/logout-request';
export type { PageResponseDocumentResponse } from './models/page-response-document-response';
export type { PageResponseImpactStoryResponse } from './models/page-response-impact-story-response';
export type { PageResponseInquiryResponse } from './models/page-response-inquiry-response';
export type { PageResponseProgramResponse } from './models/page-response-program-response';
export type { PageResponseStaffProfileResponse } from './models/page-response-staff-profile-response';
export type { PageResponseUserProfile } from './models/page-response-user-profile';
export type { PageResponseUserResponse } from './models/page-response-user-response';
export type { PreSignedUrlDto } from './models/pre-signed-url-dto';
export type { ProgramResponse } from './models/program-response';
export type { RefreshRequest } from './models/refresh-request';
export type { ResetEmailRequest } from './models/reset-email-request';
export type { ResetPasswordRequest } from './models/reset-password-request';
export type { StaffProfileResponse } from './models/staff-profile-response';
export type { TextDto } from './models/text-dto';
export type { UpdateInquiryRequest } from './models/update-inquiry-request';
export type { UserProfile } from './models/user-profile';
export type { UserResponse } from './models/user-response';
