/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseImpactStoryResponse } from '../../models/page-response-impact-story-response';

export interface GetPagesOfImpactStories$Params {
  name?: string;
  gender?: string;
  'public-id'?: string;
  page?: number;
  size?: number;
}

export function getPagesOfImpactStories(http: HttpClient, rootUrl: string, params?: GetPagesOfImpactStories$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseImpactStoryResponse>> {
  const rb = new RequestBuilder(rootUrl, getPagesOfImpactStories.PATH, 'get');
  if (params) {
    rb.query('name', params.name, {});
    rb.query('gender', params.gender, {});
    rb.query('public-id', params['public-id'], {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseImpactStoryResponse>;
    })
  );
}

getPagesOfImpactStories.PATH = '/impact-stories/pages';
