/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ImpactStatisticsResponse } from '../../models/impact-statistics-response';

export interface GetImpactStatistics$Params {
  year?: number;
  'last-days'?: number;
}

export function getImpactStatistics(http: HttpClient, rootUrl: string, params?: GetImpactStatistics$Params, context?: HttpContext): Observable<StrictHttpResponse<ImpactStatisticsResponse>> {
  const rb = new RequestBuilder(rootUrl, getImpactStatistics.PATH, 'get');
  if (params) {
    rb.query('year', params.year, {});
    rb.query('last-days', params['last-days'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ImpactStatisticsResponse>;
    })
  );
}

getImpactStatistics.PATH = '/impact-stories/statistics';
